### ISSUE TITLE
Copying dll to separate project not working 

### ISSUE THREAD

**Issue by AnandMWio** [because-why-not/uwebrtc_visionpro_testproj#2]
I think because of the missing dll its not working for me, i placed the dll with other files , i have webrtc plugin placed under package folder

```
DllNotFoundException: Unable to load DLL 'webrtc'. Tried the load the following dynamic libraries: Unable to load dynamic library '/webrtc' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen(/webrtc, 0x0005): tried: '/webrtc' (no such file)
  at Unity.WebRTC.NativeMethods.RegisterDebugLog (Unity.WebRTC.DelegateDebugLog func, System.Boolean enableNativeLog, Unity.WebRTC.NativeLoggingSeverity nativeLoggingSeverity) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.WebRTC.WebRTC.InitializeInternal (System.Boolean limitTextureSize, System.Boolean enableNativeLog, Unity.WebRTC.NativeLoggingSeverity nativeLoggingSeverity) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.WebRTC.ContextManager.Init () [0x00000] in <00000000000000000000000000000000>:0 
```

**Comment by devluz** [comment]
Can you try moving the entire webrtc folder? This looks to me like the plugin is combined with the official C# files. As result the C# side will try to load the plugin in the wrong way.

**Comment by AnandMWio** [comment]
> Can you try moving the entire webrtc folder? This looks to me like the plugin is combined with the official C# files. As result the C# side will try to load the plugin in the wrong way.

Thanks, that solved the dllnotfound issue , do you know why my app is crashing, i'm just seeing this warning in the log
`Execution of the command buffer was aborted due to an error during execution. Insufficient Permission (to submit GPU work from background)`

**Comment by devluz** [comment]
Not sure. I don't think I have seen this before. Maybe there are any warnings / errors further up in the log that can give more detail?

**Comment by AnandMWio** [comment]
> Not sure. I don't think I have seen this before. Maybe there are any warnings / errors further up in the log that can give more detail?

Now i can run the app without any crash but i'm cast see the video stream , it works in unity editor not in simulator or the device. 

i'm seeing this error message  `
(media_session.cc:952): RED codec red is missing an associated payload type.`

i think its a codec issue , does h264 is supported on VIsionOs ?

**Comment by devluz** [comment]
To what other system do you connect? It should default to VP8 which is always available (at least for libwebrtc and browsers)

h264 is not included in the built. You can try the one with hardware codecs though: https://github.com/because-why-not/uwebrtc_visionpro_testproj/tree/v0.0.1_release_hwcodecs

Can you confirm that it works with VP8? Adding hardware codecs introduces a new source of device specific errors and there a few compiler and runtime errors connected to it. 

You can also build it from scratch here if you need to customize any build flags: https://github.com/because-why-not/uwebrtc_visionpro/tree/main_hw_codec_test

**Comment by AnandMWio** [comment]
The HwCodecs works fine for:) , but for me somehow it only works in VR mode, i cant see the streaming video in MR or PolySpatial mode of Vision pro, audio works fine in both mode . 
do you have any clue why video is not visible in MR mode. 
Kudos!!!!! 👍

**Comment by AnandMWio** [comment]
Never mind, it seems working fine.
